name: show git tag diff

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      useTag: 
        description: 'If True, return the commits during the second latest tag and the latest tag.'
        type: boolean
        required: true
        default: true
      start:
        description: 'Input commit hash or tag. Required if useTag is false. '
        type: string
        required: false
      end: 
        description: 'Input commit hash or tag. Required if useTag is false. '
        type: string
        required: false

jobs:
  show-git-tag-diff:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0 # actions/checkout@v3は最新コミットしかcloneしない。
      - name: diff
        run: |
          USERNAME=${GITHUB_REPOSITORY%%/*}
          REPONAME=${GITHUB_REPOSITORY##*/}
          git ls-remote https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${USERNAME}/${REPONAME}.git
          git ls-remote https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${USERNAME}/${REPONAME}.git --tags

      # - name: diff
      #   run: |
      #     if ${{ inputs.useTag }} ; then
      #       tags=($(git tag --sort=-authordate | head -n 2))
      #       git log --pretty=oneline ${tags[0]}...${tags[1]} | awk '{print $1}'
      #     else
      #       git log --pretty=oneline ${{ inputs.start }}...${{ inputs.end }} | awk '{print $1}'
      #     fi

