name: show git tag diff

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      useTag: 
        description: 'Trueなら1つ前のタグ <= 最新のタグ間のコミットIDを出力'
        type: boolean
        required: true
        default: true
      start:
        description: 'コミットIDかタグ。start <= end間のコミットIDを出力。useTagがFalseなら必須'
        type: string
        required: false
      end: 
        description: 'コミットIDかタグ。start <= end間のコミットIDを出力。useTagがFalseなら必須'
        type: string
        required: false

jobs:
  show-git-tag-diff:
    runs-on: ubuntu-latest
    steps:
      - name: diff
        # クローンせずに頑張る
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          USERNAME=${GITHUB_REPOSITORY%%/*}
          REPONAME=${GITHUB_REPOSITORY##*/}
          if ${{ inputs.useTag }} ; then          
            tags=($(git ls-remote --tags https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${USERNAME}/${REPONAME}.git | tail -n 2 | awk '{print $2}'))
            gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${USERNAME}/${REPONAME}/compare/${tags[0]}...${tags[1]} | jq '.commits[].sha' | tr -d '"'

          else
            gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${USERNAME}/${REPONAME}/compare/${{ inputs.start }}...${{ inputs.end }} | jq '.commits[].sha' | tr -d '"'
          fi
